/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:73edf8dc-12ee-4b7f-aa9f-10207b2d9a21",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vG7F1qnOM",
    "aws_user_pools_web_client_id": "4o2lknetb5bnl8uocu1304edoo",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "NAME",
        "PHONE_NUMBER"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 6,
        "passwordPolicyCharacters": [
            "REQUIREUPPERCASE",
            "REQUIRELOWERCASE",
            "REQUIRENUMBERS",
            "REQUIRESYMBOLS"
        ]
    },
    "aws_cognito_verification_mechanisms": [],
    "aws_appsync_graphqlEndpoint": "https://2sqfkbscznbzzadb2fusoq6jj4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://1u81d8ilm5.execute-api.us-east-1.amazonaws.com/prd",
            "region": "us-east-1"
        }
    ],
    "aws_user_files_s3_bucket": "udnas3prd-prd",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
